# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

matrix:
  include:
    - os: linux
      r: devel
      compiler: gcc
      after_success:
        - Rscript -e 'covr::codecov()'

    - os: linux
      r: release
      compiler: clang

    - os: linux
      r: oldrel
      compiler: gcc

    - os: osx
      r: release
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

    - os: osx
      r: oldrel
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

