# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FitModel <- function(x, y, family_in, fit_intercept, is_sparse, alpha, beta, normalize, max_iter, tol) {
    .Call(`_sgdnet_FitModel`, x, y, family_in, fit_intercept, is_sparse, alpha, beta, normalize, max_iter, tol)
}

